rootProject.name = "hex-thai-star"

include(":booking-api-out")
include(":booking-adapter-out-jdbi")
include(":order-application")
include(":booking-adapter-out-quarkusmail")
include(":common-domain")
include(":order-domain")
include(":booking-adapter-in-springweb")
include(":order-adapter-out-jpa")
include(":awslambda")
include(":common-adapter-out-jdbi")
include(":booking-adapter-in-quarkusweb")
include(":booking-adapter-out-springmail")
include(":springboot")
include(":booking-adapter-out-awsmail")
include(":booking-application")
include(":order-adapter-in-springweb")
include(":order-api-out")
include(":quarkus")
include(":order-api-in")
include(":order-adapter-out-booking")
include(":quarkus-awslambda")
include(":booking-adapter-out-dynamodb")
include(":booking-adapter-in-awslambda")
include(":booking-adapter-out-jpa")
include(":archunit")
include(":common-application")
include(":booking-domain")
include(":booking-api-in")

project(":booking-api-out").projectDir = file("booking/booking-api-out")
project(":booking-adapter-out-jdbi").projectDir = file("booking/booking-adapter-out-jdbi")
project(":order-application").projectDir = file("order/order-application")
project(":booking-adapter-out-quarkusmail").projectDir = file("booking/booking-adapter-out-quarkusmail")
project(":common-domain").projectDir = file("common/common-domain")
project(":order-domain").projectDir = file("order/order-domain")
project(":booking-adapter-in-springweb").projectDir = file("booking/booking-adapter-in-springweb")
project(":order-adapter-out-jpa").projectDir = file("order/order-adapter-out-jpa")
project(":awslambda").projectDir = file("configuration/awslambda")
project(":common-adapter-out-jdbi").projectDir = file("common/common-adapter-out-jdbi")
project(":booking-adapter-in-quarkusweb").projectDir = file("booking/booking-adapter-in-quarkusweb")
project(":booking-adapter-out-springmail").projectDir = file("booking/booking-adapter-out-springmail")
project(":springboot").projectDir = file("configuration/springboot")
project(":booking-adapter-out-awsmail").projectDir = file("booking/booking-adapter-out-awsmail")
project(":booking-application").projectDir = file("booking/booking-application")
project(":order-adapter-in-springweb").projectDir = file("order/order-adapter-in-springweb")
project(":order-api-out").projectDir = file("order/order-api-out")
project(":quarkus").projectDir = file("configuration/quarkus")
project(":order-api-in").projectDir = file("order/order-api-in")
project(":order-adapter-out-booking").projectDir = file("order/order-adapter-out-booking")
project(":quarkus-awslambda").projectDir = file("configuration/quarkus-awslambda")
project(":booking-adapter-out-dynamodb").projectDir = file("booking/booking-adapter-out-dynamodb")
project(":booking-adapter-in-awslambda").projectDir = file("booking/booking-adapter-in-awslambda")
project(":booking-adapter-out-jpa").projectDir = file("booking/booking-adapter-out-jpa")
project(":archunit").projectDir = file("configuration/archunit")
project(":common-application").projectDir = file("common/common-application")
project(":booking-domain").projectDir = file("booking/booking-domain")
project(":booking-api-in").projectDir = file("booking/booking-api-in")
