logging:
  level:
    root: INFO
    web: DEBUG
    org:
      hibernate:
        type: DEBUG
        SQL: DEBUG

server:
  port: 7777

booking:
  store: jpa

spring:
  mail:
    host: localhost
    port: 30025
